# Generated by Django 4.2.4 on 2023-09-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_copytradetxhash_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Txhash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Txhash', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
