# Generated by Django 4.2.4 on 2023-09-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_txhash'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyContractToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=500)),
                ('token_address', models.CharField(blank=True, max_length=500)),
                ('limit', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('check_limit', models.BooleanField(default=False)),
                ('profit', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('check_profit', models.BooleanField(default=False)),
                ('stop_loss', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('check_stop_loss', models.BooleanField(default=False)),
                ('gas_delta', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('slippage', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
            ],
        ),
    ]
